<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class CarsTableSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $cars = [
            [
                'brand' => 'Toyota',
                'model' => 'Corolla',
                'description' => 'A reliable sedan, perfect for daily commuting.',
                'year' => 2021,
                'transmission' => 'Automatic',
                'body_type' => 'Sedan',
                'color' => 'White',
                'fuel' => 'Petrol',
                'engine_size' => '1.8L',
                'seats' => 5,
                'doors' => 4,
                'drive_type' => 'FWD',
                'condition' => 'Used',
                'mileage' => 25000,
                'images' => json_encode([
                    'images/toyota_corolla_1.jpg',
                    'images/toyota_corolla_2.jpg'
                ]),
                'video' => 'videos/toyota_corolla.mp4',
                'created_at' => $now,
                'updated_at' => $now,
                'price' => 18000,
                'seller_type' => 'private',
                'user_id' => 1,
                'status' => 'pending',
                'is_featured' => false,
                'price_type' => 'fixed',
                'sale_rent' => 'sale',
                'deleted_at' => null,
                'approved_at' => null,
                'approved_by' => null,
                'rejection_reason' => null,
            ],
            [
                'brand' => 'Honda',
                'model' => 'Civic',
                'description' => 'Sporty sedan with great fuel efficiency.',
                'year' => 2020,
                'transmission' => 'Manual',
                'body_type' => 'Sedan',
                'color' => 'Red',
                'fuel' => 'Petrol',
                'engine_size' => '2.0L',
                'seats' => 5,
                'doors' => 4,
                'drive_type' => 'FWD',
                'condition' => 'Used',
                'mileage' => 30000,
                'images' => json_encode([
                    'images/honda_civic_1.jpg',
                    'images/honda_civic_2.jpg'
                ]),
                'video' => 'videos/honda_civic.mp4',
                'created_at' => $now,
                'updated_at' => $now,
                'price' => 19000,
                'seller_type' => 'private',
                'user_id' => 1,
                'status' => 'pending',
                'is_featured' => true,
                'price_type' => 'fixed',
                'sale_rent' => 'sale',
                'deleted_at' => null,
                'approved_at' => null,
                'approved_by' => null,
                'rejection_reason' => null,
            ],
            [
                'brand' => 'BMW',
                'model' => 'X5',
                'description' => 'Luxury SUV with premium features.',
                'year' => 2022,
                'transmission' => 'Automatic',
                'body_type' => 'SUV',
                'color' => 'Black',
                'fuel' => 'Diesel',
                'engine_size' => '3.0L',
                'seats' => 5,
                'doors' => 5,
                'drive_type' => 'AWD',
                'condition' => 'New',
                'mileage' => 5000,
                'images' => json_encode([
                    'images/bmw_x5_1.jpg',
                    'images/bmw_x5_2.jpg'
                ]),
                'video' => 'videos/bmw_x5.mp4',
                'created_at' => $now,
                'updated_at' => $now,
                'price' => 60000,
                'seller_type' => 'broker',
                'user_id' => 1,
                'status' => 'pending',
                'is_featured' => true,
                'price_type' => 'fixed',
                'sale_rent' => 'sale',
                'deleted_at' => null,
                'approved_at' => null,
                'approved_by' => null,
                'rejection_reason' => null,
            ],
            [
                'brand' => 'Mercedes',
                'model' => 'C-Class',
                'description' => 'Elegant sedan for comfort and style.',
                'year' => 2019,
                'transmission' => 'Automatic',
                'body_type' => 'Sedan',
                'color' => 'Silver',
                'fuel' => 'Petrol',
                'engine_size' => '2.0L',
                'seats' => 5,
                'doors' => 4,
                'drive_type' => 'RWD',
                'condition' => 'Used',
                'mileage' => 40000,
                'images' => json_encode([
                    'images/mercedes_c_1.jpg'
                ]),
                'video' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'price' => 35000,
                'seller_type' => 'broker',
                'user_id' => 1,
                'status' => 'pending',
                'is_featured' => false,
                'price_type' => 'negotiable',
                'sale_rent' => 'sale',
                'deleted_at' => null,
                'approved_at' => null,
                'approved_by' => null,
                'rejection_reason' => null,
            ],
            [
                'brand' => 'Audi',
                'model' => 'A4',
                'description' => 'Compact executive car with sporty design.',
                'year' => 2021,
                'transmission' => 'Automatic',
                'body_type' => 'Sedan',
                'color' => 'Blue',
                'fuel' => 'Petrol',
                'engine_size' => '2.0L',
                'seats' => 5,
                'doors' => 4,
                'drive_type' => 'FWD',
                'condition' => 'Used',
                'mileage' => 22000,
                'images' => json_encode([
                    'images/audi_a4_1.jpg',
                    'images/audi_a4_2.jpg'
                ]),
                'video' => 'videos/audi_a4.mp4',
                'created_at' => $now,
                'updated_at' => $now,
                'price' => 28000,
                'seller_type' => 'dealership',
                'user_id' => 1,
                'status' => 'pending',
                'is_featured' => false,
                'price_type' => 'fixed',
                'sale_rent' => 'sale',
                'deleted_at' => null,
                'approved_at' => null,
                'approved_by' => null,
                'rejection_reason' => null,
            ],
        ];

        DB::table('cars')->insert($cars);
    }
}
