<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\House;
use Illuminate\Support\Str;

class HousesSeeder extends Seeder
{
    public function run()
    {
        $userId = 1; // assuming the owner user created in UsersSeeder has ID 1

        $houses = [
            [
                'user_id' => $userId,
                'title_en' => 'Luxury Villa in Addis Ababa',
                'title_am' => 'የላክሽሪ ቪላ በአዲስ አበባ',
                'description_en' => 'Beautiful 5-bedroom villa with modern amenities.',
                'description_am' => 'ቆንጆ 5 መኝታ ቪላ ከዘመናዊ አገልግሎቶች ጋር።',
                'purpose' => 'for_sale',
                'price' => '250000',
                'negotiable' => true,
                'installment' => false,
                'region' => 'Addis Ababa',
                'city_en' => 'Addis Ababa',
                'city_am' => 'አዲስ አበባ',
                'subcity_en' => 'Bole',
                'subcity_am' => 'ቦሌ',
                'address' => '123 Luxury Street',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area_m2' => 350,
                'parking' => 2,
                'property_type' => 'Villa',
                'built_year' => 2020,
                'floors' => 2,
                'garage' => true,
                'amenities' => ['Pool', 'Garden', 'Gym'],
                'images' => ['houses/sample1.jpg', 'houses/sample2.jpg'],
                'seller_type' => 'owner',
                'contact_phone' => '+251912345678',
                'contact_email' => 'owner@example.com',
                'verified' => true,
                'slug' => Str::slug('Luxury Villa in Addis Ababa'),
                'meta' => ['featured' => true, 'highlighted' => false],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'title_en' => 'Modern Apartment in Bole',
                'title_am' => 'ዘመናዊ አፓርታማ በቦሌ',
                'description_en' => '3-bedroom apartment with city view.',
                'description_am' => '3 መኝታ አፓርታማ ከከተማ እይታ ጋር።',
                'purpose' => 'for_rent',
                'price' => '1500',
                'negotiable' => false,
                'installment' => true,
                'region' => 'Addis Ababa',
                'city_en' => 'Addis Ababa',
                'city_am' => 'አዲስ አበባ',
                'subcity_en' => 'Bole',
                'subcity_am' => 'ቦሌ',
                'address' => '45 Modern Avenue',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_m2' => 120,
                'parking' => 1,
                'property_type' => 'Apartment',
                'built_year' => 2018,
                'floors' => 1,
                'garage' => false,
                'amenities' => ['Elevator', 'Balcony', 'Security'],
                'images' => ['houses/sample3.jpg', 'houses/sample4.jpg'],
                'seller_type' => 'owner',
                'contact_phone' => '+251911223344',
                'contact_email' => 'owner@example.com',
                'verified' => true,
                'slug' => Str::slug('Modern Apartment in Bole'),
                'meta' => ['featured' => false, 'highlighted' => true],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'title_en' => 'Cozy Guest House',
                'title_am' => 'ማቀነባበሪያ ጋር ታላቅ ቤት',
                'description_en' => 'Guest house suitable for tourists.',
                'description_am' => 'ለጉብኝት ተስማሚ አማራጭ ቤት።',
                'purpose' => 'for_rent',
                'price' => '800',
                'negotiable' => true,
                'installment' => false,
                'region' => 'Addis Ababa',
                'city_en' => 'Addis Ababa',
                'city_am' => 'አዲስ አበባ',
                'subcity_en' => 'Kirkos',
                'subcity_am' => 'ክርቆስ',
                'address' => '12 Cozy Lane',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_m2' => 80,
                'parking' => 0,
                'property_type' => 'Guest House',
                'built_year' => 2015,
                'floors' => 1,
                'garage' => false,
                'amenities' => ['WiFi', 'Air Conditioning'],
                'images' => ['houses/sample5.jpg'],
                'seller_type' => 'owner',
                'contact_phone' => '+251910998877',
                'contact_email' => 'owner@example.com',
                'verified' => true,
                'slug' => Str::slug('Cozy Guest House'),
                'meta' => ['featured' => false],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'title_en' => 'Commercial Office Space',
                'title_am' => 'ንግድ ቢሮ ቦታ',
                'description_en' => 'Office space in city center.',
                'description_am' => 'ቢሮ ቦታ በከተማ ማዕከል።',
                'purpose' => 'for_rent',
                'price' => '3000',
                'negotiable' => false,
                'installment' => true,
                'region' => 'Addis Ababa',
                'city_en' => 'Addis Ababa',
                'city_am' => 'አዲስ አበባ',
                'subcity_en' => 'Addis Ketema',
                'subcity_am' => 'አዲስ ከተማ',
                'address' => '77 Office Street',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'area_m2' => 200,
                'parking' => 2,
                'property_type' => 'Commercial',
                'built_year' => 2010,
                'floors' => 1,
                'garage' => true,
                'amenities' => ['Conference Room', 'Parking', 'CCTV'],
                'images' => ['houses/sample6.jpg'],
                'seller_type' => 'owner',
                'contact_phone' => '+251911556677',
                'contact_email' => 'owner@example.com',
                'verified' => true,
                'slug' => Str::slug('Commercial Office Space'),
                'meta' => ['featured' => false],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userId,
                'title_en' => 'Land Plot in Bole',
                'title_am' => 'መሬት ቦሌ',
                'description_en' => 'Plot suitable for residential building.',
                'description_am' => 'ለመኖር ቤት ተስማሚ መሬት።',
                'purpose' => 'for_sale',
                'price' => '100000',
                'negotiable' => true,
                'installment' => true,
                'region' => 'Addis Ababa',
                'city_en' => 'Addis Ababa',
                'city_am' => 'አዲስ አበባ',
                'subcity_en' => 'Bole',
                'subcity_am' => 'ቦሌ',
                'address' => 'Plot 55',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'area_m2' => 500,
                'parking' => 0,
                'property_type' => 'Land / Plot',
                'built_year' => null,
                'floors' => null,
                'garage' => false,
                'amenities' => [],
                'images' => ['houses/sample7.jpg'],
                'seller_type' => 'owner',
                'contact_phone' => '+251912334455',
                'contact_email' => 'owner@example.com',
                'verified' => true,
                'slug' => Str::slug('Land Plot in Bole'),
                'meta' => ['featured' => false],
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($houses as $house) {
            House::create($house);
        }
    }
}
